name: Build and Publish Docker image

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 23 * * *"

jobs:
  build_and_push:
    name: Build and Push to ghcr.io
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/devlincashman/samba
          tags: | 
            type=sha,enable=true,priority=100,prefix=,suffix=,format=short
            type=schedule,pattern=nightly
          flavor: latest=true

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/386,linux/ppc64le,linux/s390x
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
